"""Agregar campo output_jenkins al modelo Resultado

Revision ID: 1eae05ea451f
Revises: 3a8b9f0c1d2e
Create Date: 2026-06-01 11:29:23.071449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eae05ea451f'
down_revision = '3a8b9f0c1d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caso_prueba', schema=None) as batch_op:
        batch_op.alter_column('requiere_intento_manual',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))

    with op.batch_alter_table('resultado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_jenkins', sa.Text(), nullable=True))
        batch_op.alter_column('modo_ejecucion',
               existing_type=sa.VARCHAR(length=12),
               nullable=True,
               existing_server_default=sa.text("'manual'"))
        batch_op.alter_column('estado_ejecucion',
               existing_type=sa.VARCHAR(length=11),
               nullable=True,
               existing_server_default=sa.text("'completado'"))
        batch_op.alter_column('numero_intentos',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultado', schema=None) as batch_op:
        batch_op.alter_column('numero_intentos',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('estado_ejecucion',
               existing_type=sa.VARCHAR(length=11),
               nullable=False,
               existing_server_default=sa.text("'completado'"))
        batch_op.alter_column('modo_ejecucion',
               existing_type=sa.VARCHAR(length=12),
               nullable=False,
               existing_server_default=sa.text("'manual'"))
        batch_op.drop_column('output_jenkins')

    with op.batch_alter_table('caso_prueba', schema=None) as batch_op:
        batch_op.alter_column('requiere_intento_manual',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
