"""Agregar id_solicitud y hacer ciclo_prueba_id nullable

Revision ID: 2f749fedc46b
Revises: 
Create Date: 2026-05-29 16:05:17.754880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f749fedc46b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_solicitud', sa.String(length=36), nullable=True))
        batch_op.alter_column('ciclo_prueba_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint('uq_resultado_id_solicitud', ['id_solicitud'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultado', schema=None) as batch_op:
        batch_op.drop_constraint('uq_resultado_id_solicitud', type_='unique')
        batch_op.alter_column('ciclo_prueba_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('id_solicitud')

    # ### end Alembic commands ###
