"""add tiempo_ejecucion to resultado

Revision ID: d0d5f8e4a151
Revises: 1eae05ea451f
Create Date: 2026-06-01 12:05:32.993054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0d5f8e4a151'
down_revision = '1eae05ea451f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tiempo_ejecucion', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resultado', schema=None) as batch_op:
        batch_op.drop_column('tiempo_ejecucion')

    # ### end Alembic commands ###
